name: linting_and_testing

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.3
      - name: setup environment
        run: poetry install
      - name: flake8
        run: poetry run flake8
      - name: pytest
        run: poetry run pytest
