name: pypi_release

on:
  release:
    types: [published]

jobs:
  pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
      - name: publish
        env:
          USERNAME: ${{ secrets.PYPI_USERNAME }}
          PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: pdm publish --username $USERNAME --password $PASSWORD
